version: '3.7'
services:
#application layer
  appweb:
    image: efdaimon/testcase:appimage
    build: .
    ports:
      - '81:80'
      - '82:80'
#proxy for the application layer
  loadbalancer:
    image: nginx:latest
    ports:
      - '80:80'
#database service
  mysql:
    image: mysql:latest
    environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: db
#Deactivated on purpose since requires at least: vm.max_map_count = 262144
#  elastic:
#    image: bitnami/elasticsearch:latest
#    ports:
#      - '6200:6200'
#    volumes:
#      - /path/to/elasticsearch-data-persistence:/bitnami/elasticsearch/data
